CMS/CMS/CMS/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

]

CMS/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('map.urls', namespace='map')),
    path('callcentre/', include('callcentre.urls', namespace='callcentre')),
    path('statustrack/', include('statusTrack.urls', namespace='statustrack')),
    path('incidentCreation/', include('incidentCreation.urls', namespace='incidentCreation')),
]

callcentre/urls.py
from django.urls import path
from . import views

app_name = 'callcentre'

urlpatterns = [
    path('', views.callcentre_home, name='callcentre_home'),
    path('history/', views.callcentre_history, name='callcentre_history'),
]

incidentCreation/urls.py
from django.urls import path
from . import views

app_name = 'incidentCreation'

urlpatterns = [
    path('', views.incidentCreation, name='incidentCreation'),
]

map/urls.py
from django.urls import path
from map.views import LocationFormView
from . import views

app_name = 'map'

urlpatterns = [
    path('', LocationFormView.as_view(), name='map_home'),
]

statusTrack/urls.py
from django.urls import path
from . import views

app_name = 'statusTrack'

urlpatterns = [
    path('', views.statusTrack, name='statusTrack'),
]

callcentre/models.py
from django.db import models
from django.urls import reverse
from utilities.incidentstatus import IncidentStatus
from utilities.incidenttype import IncidentType
from utilities.region import Region
from django.utils import timezone

CATEGORY_CHOICES = [    # Note square brackets.
    ("Emergency Ambulance", "Emergency Ambulance"), 
    ("Rescue & Evacuation", "Rescue & Evacuation"),
    ("Fire Fighting", "Fire Fighting"),
    ("Gas Leak Control", "Gas Leak Control"),        
]


TYPE_CHOICES = [
    ("--------Emergency Situations--------", "--------Emergency Situations--------"),
    ("----Natural Hazards----", "----Natural Hazards----"),
    ("Fire", "Fire"),
    ("Haze", "Haze"),
    ("Tsunami", "Tsunami"),
    ("Typhoon", "Typhoon"),
    ("Earthquake", "Earthquake"),
    ("Earthquake Aftershocks", "Earthquake Aftershocks"),
    ("----Epidemic----", "----Epidemic----"),
    ("Dengue", "Dengue"),
    ("HIV/AIDS", "HIV/AIDS"),
    ("Bird-flu", "Bird-flu"),
    ("Zika", "Zika"),
    ("----Traffic Accidents----","----Traffic Accidents----"),
    ("Single Car Accidents","Single Car Accidents"),
    ("Two Car Collisions","Two Car Collisions"),
    ("Multiple Vehicle Pile-up","Multiple Vehicle Pile-up"),
    ("----Incidents within Crowded Areas----", "----Incidents within Crowded Areas----"),
    ("Terrorist Attacks","Terrorist Attacks"),
    ("Mass Shooting","Mass Shooting"),
    ("Other Useful Information", "Other Useful Information"),
    ("Weather", "Weather"),
    ("Civil Defense Shelters", "Civil Defense Shelters"),
]

STATUS_UPDATE = [
    ("New", "New"),
    ("Planned", "Planned"),
    ("In Progress", "In Progress"),
    ("Resolved", "Resolved"),
]

class Incident(models.Model):
    caller_name = models.CharField(max_length=50, default='NULL')
    mobile_number = models.CharField(max_length=8, default='NULL')
    incident_time = models.DateTimeField(default=timezone.now)
    incident_location = models.CharField(max_length=100, default='NULL')
    incident_department = models.CharField(max_length=100, default='NULL')
    incident_region = models.CharField(max_length=100, choices=[(tag, tag.value) for tag in Region], default='NULL')
    incident_category = models.CharField(max_length=100, choices=CATEGORY_CHOICES, default='NULL')
    incident_type = models.CharField(max_length=100, choices=TYPE_CHOICES, default='NULL')
    incident_status = models.CharField(max_length=100, choices=STATUS_UPDATE, default='NEW')
    incident_description = models.CharField(max_length=400, default='NULL')

incidentCreation/models.py
from django.db import models
from django import forms
import sys, os


sys.path.append(os.path.abspath(os.path.join('..', 'callcentre')))

from callcentre.models import Incident

class ContactForm2(forms.ModelForm):
    class Meta:
        model=Incident                   
        fields=('caller_name','mobile_number', 'incident_location', 'incident_type','incident_category') 

map/models.py
from django.db import models
from django_google_maps import fields as map_fields
# Create your models here.


class LocationModel(models.Model):
    address = map_fields.AddressField(max_length=200)
    geolocation = map_fields.GeoLocationField(max_length=100)

    def __str__(self):
        return self.address


class Test(models.Model):
    place = models.CharField(max_length=100)
    category = models.CharField(max_length=100)

statusTrack/models.py
from django.db import models
from django import forms
import sys, os


sys.path.append(os.path.abspath(os.path.join('..', 'callcentre')))

from callcentre.models import Incident

class ContactForm3(forms.ModelForm):
    class Meta:
        model=Incident
        fields=('incident_status',)

callcentre/views.py
from django.shortcuts import render
from .models import Incident


def callcentre_home(request):
    all_unsolved_incidents = Incident.objects.exclude(incident_status='Resolved').order_by('incident_time')
    context = {'all_unsolved_incidents' : all_unsolved_incidents }
    return render(request, 'callcentre/callcentre_home.html', context)

def callcentre_history(request):
    incident_history = Incident.objects.filter(incident_status='Resolved')
    context = {'incident_history' : incident_history }
    return render(request, 'callcentre/callcentre_history.html', context)

#def status_track(request):
#    status_track = Incident.objects.filter(id)
#    context = {'status_track' : status_track}
#    return render(request, 'statustrack/statustrack_home.html',context)

incidentCreation/views.py
from django.shortcuts import render
from django import forms
from .models import Incident, ContactForm2
from django.shortcuts import render_to_response
from django.shortcuts import render
from django.template import RequestContext
from django.http import HttpResponse
from django.http import HttpResponseRedirect


def incidentCreation(request):
	if request.method=='GET':
		form = ContactForm2(request.GET)											
		if form.is_valid():
			# print("The form is valid\n\n\n\n")
			incident = Incident()
			incident.caller_name = form.cleaned_data['caller_name']
			incident.mobile_number = form.cleaned_data['mobile_number']
			incident.incident_location = form.cleaned_data['incident_location']
			incident.incident_category = form.cleaned_data['incident_category']
			incident.incident_type = form.cleaned_data['incident_type']
			incident.save()
			# print("A new incident is saved\n\n\n\n")
			return render_to_response('callcentre/incidentCreation.html',{'form':form},RequestContext(request))
		else:
			form=ContactForm2()
			return render_to_response('callcentre/incidentCreation.html',{'form':form},RequestContext(request))

map/views.py
from django.shortcuts import render
from django.views.generic import FormView
from map.form import LocationForm
from .models import Test
from callcentre.models import Incident
from django.core.serializers.json import DjangoJSONEncoder
import json


class LocationFormView(FormView):
    form_class = LocationForm
    template_name = "map/map_home.html"

    def get_context_data(self, **kwargs):
        context = super(LocationFormView, self).get_context_data(**kwargs)
        incidents = Incident.objects.all()
        # locations_json = json.dumps(list(locations), cls=DjangoJSONEncoder)
        context['incidents'] = incidents # allow template to utilize incidents
        context['type'] = ' '
        return context

statusTrack/views.py
from django.shortcuts import render
from django import forms
from callcentre.models import Incident
from .models import ContactForm3
from django.shortcuts import render_to_response
from django.shortcuts import render
from django.template import RequestContext
from django.http import HttpResponse
from django.http import HttpResponseRedirect


def statusTrack(request):
	if request.method=='GET':
		form = ContactForm3(request.GET)
		if form.is_valid():
			# print("The form is valid\n\n\n\n")
			incident = Incident.objects.get(id=4)
			incident.incident_status = form.cleaned_data['incident_status']
			incident.save()
			# print("A new incident is saved\n\n\n\n")
			return render_to_response('statustrack/statustrack_home.html',{'form':form},RequestContext(request))
		else:
			form=ContactForm3()
			return render_to_response('statustrack/statustrack_home.html',{'form':form},RequestContext(request))

django_google_maps/templates/django_google_maps/widgets/map_widget.html
{% include "django/forms/widgets/text.html" %}
<div class="map_canvas_wrapper"><div id="map_canvas"></div></div>

templates/base_navi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'map:map_home' %}">Homepage</a>
        </div>

        <!--items-->
        <div class="collapse navbar-collapse topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'callcentre:callcentre_home' %}">
                        <span class="fas fa-phone"></span>&nbsp; Call Centre
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Log off
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/callcentre/callcentre_history.html
{% extends 'base_navi.html' %}

{% block body %}
<h1>Here list all the resolved incidents</h1>
<table style="width:100%">
  <tr>
    <th>Incident ID</th>
    <th>Type</th>
    <th>Time</th>
    <th>Location</th>
    <th>Department</th>
  </tr>
 {% for incident in incident_history %}
  <tr>
    <td>{{ incident.id }}</td>
    <td>{{ incident.incident_category }}</td>
    <td>{{ incident.incident_time }}</td>
    <td>{{ incident.incident_location }}</td>
    <td>{{ incident.incident_department }}</td>
  </tr>
    {% endfor %}
</table>
<a class="btn btn-default" href="{% url 'callcentre:callcentre_home' %}" role="button">Back</a>
{% endblock %}

templates/callcentre/callcentre_home.html
{% extends 'base_navi.html' %}

{% block body %}
<h1>Call Centre Homepage</h1>
<h2>Here displays all the unresolved incidents.</h2>
<table style="width:100%">
  <tr>
    <th>Incident ID</th>
    <th>Type</th>
    <th>Time</th>
    <th>Location</th>
    <th>Status</th>
    <th>Department</th>
  </tr>
 {% for incident in all_unsolved_incidents %}
  <tr>
    <td>{{ incident.id }}</td>
    <td>{{ incident.incident_category }}</td>
    <td>{{ incident.incident_time }}</td>
    <td>{{ incident.incident_location }}</td>
    <td>{{ incident.incident_status }}</td>
    <td>{{ incident.incident_department }}</td>
  </tr>
    {% endfor %}
</table>
<a class="btn btn-default" href="{% url 'incidentCreation:incidentCreation' %}"  role="button">Create incidents</a>
<a class="btn btn-default" href="{% url 'callcentre:callcentre_history' %}" role="button">History</a>
<a class="btn btn-default" href="{% url 'statusTrack:statusTrack' %}"  role="button">Update status</a>
{% endblock %}

templates/callcentre/incidentCreation.html
{% extends 'base_navi.html' %}

{% block body %}

<script>
function sumbit_sure(){
var gnl=confirm("Confirm to submit?");
if (gnl==true){
return true;
}else{
return false;
}
}
</script>

<h1>Create a New Incident</h1>
  <form action="/incidentCreation"  method="GET" onsubmit="return sumbit_sure()">
    {% for field in form %} 
    <div class="fieldWrapper">
     {{ field.label_tag }}:{{ field }} {{ field.errors }} 
    </div>
    {% endfor %} 
    <div class="fieldWrapper">
    <p><input type="submit" value="Submit"/><div>

  </form>
{% endblock %}

templates/map/map_home.html
{% extends 'base_navi.html' %}
{% block body %}
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #dddddd;
}
</style>
<select id="category" onchange="location.reload()">
    <option value="Emergency Situations" >--------Emergency Situations--------</option>

    <option value="Natural Hazards">----Natural Hazards----</option>
    <option value="Fire">Fire</option>
    <option value="Haze">Haze</option>
    <option value="Tsunami">Tsunami</option>
    <option value="Typhoon">Typhoon</option>
    <option value="Earthquake">Earthquake</option>
    <option value="Earthquake Aftershocks">Earthquake Aftershocks</option>

    <option value="Epidemic">----Epidemic----</option>
    <option value="Dengue">Dengue</option>
    <option value="HIV/AIDS">HIV/AIDS</option>
    <option value="Bird-flu">Bird-flu</option>
    <option value="Zika">Zika</option>

    <option value="Traffic Accidents">----Traffic Accidents----</option>
    <option value="Single Car Accidents">Single Car Accidents</option>
    <option value="Two Car Collisions">Two Car Collisions</option>
    <option value="Multiple Vehicle Pile-up">Multiple Vehicle Pile-up</option>

    <option value="Incidents within Crowded Areas">----Incidents within Crowded Areas----</option>
    <option value="Terrorist Attacks">Terrorist Attacks</option>
    <option value="Mass Shooting">Mass Shooting</option>

    <option value="Other Useful Information">--------Other Useful Information--------</option>

    <option value="Weather">Weather</option>
    <option value="Civil Defense Shelters">Civil Defense Shelters</option>
</select>
<br>
<br>
<script>
    // store the value of selection to localStorage

    $(document).ready(function(){
        var selected_val = localStorage.getItem("category");
        $("#category").val(selected_val);
    $("#category").change(function(){
        var selected = $("#category").val();
        localStorage.setItem("category", selected);
        $(this).closest('form').trigger('submit');
        });
    });

    // initialize the containers for data to be used in javascript file
    var locationlist = [];
    var times = [];
    var descriptions = [];
</script>


<body>
{% for incident in incidents %}
<script>
// this script is to push all the incident of the selected type into the containers
var category = localStorage.getItem("category");
if("{{incident.incident_type}}" == String(category)){
    locationlist.push("{{incident.incident_location}}");
    //times.push("{{incident.incident_time}}"); not sure what data type will datetime be in javascript
    descriptions.push("{{incident.incident_description}}");
    }
</script>
{% endfor %}
{{form.media}}


{{form.as_p}}

<table id="display_table">
    <tr>
        <th>Type</th>
        <th>Location</th>
        <th>Department</th>
        <th>Region</th>
        <th>Status</th>
        <th>Description</th>
    </tr>

{% for incident in incidents %}
<script>
// this script is to populate the table based on the selected category
    var category = localStorage.getItem("category");
    var $table = $('#display_table');
    if("{{incident.incident_type}}" == String(category)){
         $table.append('<tr>' +
                                        '<th>' + '{{incident.incident_type}}' + '</th>' +
                                        '<th>' + '{{incident.incident_location}}' + '</th>' +
                                        '<th>' + '{{incident.incident_department}}' + '</th>' +
                                        '<th>' + '{{incident.incident_region}}' + '</th>' +
                                        '<th>' + '{{incident.incident_status}}' + '</th>' +
                                        '<th>' + '{{incident.incident_description}}' + '</th>' +
                                        '</tr>'
                                        );
    }
</script>
{% endfor %}
</table>
{% endblock %}
</body>

templates/statustrack/statustrack_home.html
{% extends 'base_navi.html' %}

{% block body %}

<script>
function sumbit_sure(){
var gnl=confirm("Confirm to update?");
if (gnl==true){
return true;
}else{
return false;
}
}
</script>

<h1>Status Track Page</h1>
<h2>Status track for unsolved incidents</h2>
  <form method="post">
    {% csrf_token %}
    <input type="text" name="" value="">
    <button type="submit">Submit</button>
  </form>
  <form action="/statustrack"  method="GET" onsubmit="return sumbit_sure()">
    {% for field in form %}
    <div class="fieldWrapper">
     {{ field.label_tag }}:{{ field }} {{ field.errors }}
    </div>
    {% endfor %}
    <div class="fieldWrapper">
    <p><input type="submit" value="Update"/><div>

  </form>
{% endblock %}